---
title: "Greenhouse Gas emissions for Annex I countries"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    theme: paper
  runtime: shiny
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(knitr)
library(cowplot)
library(ggrepel)
library(ggspatial)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(shiny)
library(leaflet)

```



```{r}
## Load in data
AnnexI_GHG.df <- readRDS("data/AnnexI_Country_GHG_Inventory.rds")

AnnexI_GHG.df <- AnnexI_GHG.df %>% 
  filter(!lg.main.sector, !grepl(pattern = "European Union", country)) %>% 
  rename(IPCC_category = sector, sector = main.sector)

## Make sector options
opt_Sector <- unique(AnnexI_GHG.df$sector) %>% as.character()
opt_Sector <- c("All", opt_Sector)


## Build unique country country.code dataframe
country.df <- AnnexI_GHG.df %>% 
  select(country.code, country) %>% 
  unique.data.frame()

## Make country selection
opt_Country <- unique(country.df$country)
opt_Country <- c("Annex I", opt_Country)


```


Inputs {.sidebar}
-------------------------------------

Select sector, years, and countries to generate maps, plots and tables of reported national greenhouse gas emissions.

```{r}
## Single selection for sector
selectInput("sel_sector", label = "Sector:",
            choices = opt_Sector, selected = "All")
```

```{r}
## Slider selection for years
sliderInput("sel_years", label = "Years:",
            min = 1990, max = 2018, value = c(1990, 2018), step = 1, dragRange = TRUE, sep = "")
```


```{r}
## Multi selection for countries
selectInput("sel_country", label = "Countries:",
            choices = opt_Country, selected = "Annex I", multiple = TRUE)
```


Row {data-height=680}
-----------------------------------------------------------------------


### World map of mean GHG emissions

```{r echo=FALSE, fig.height=5}
renderLeaflet({
print(input$sel_country)
years_seq <- seq(input$sel_years[1], input$sel_years[2], by = 1)

if(input$sel_sector == "All"){
  country.AnnexI_GHG.df <- AnnexI_GHG.df %>%
    filter(year %in% years_seq) %>% 
    group_by(year, country.code, country) %>% 
    summarise(emission.GtCO2eq = sum(emission.ktCO2eq, na.rm = TRUE)/1E6) %>%
    group_by(country.code) %>% 
    summarise(emission.GtCO2eq = mean(emission.GtCO2eq)) %>% 
    ungroup() %>% 
    rename(gu_a3 = country.code)
}else{
  country.AnnexI_GHG.df <- AnnexI_GHG.df %>% 
    filter(sector == input$sel_sector) %>% 
    filter(year %in% years_seq) %>% 
    group_by(year, country.code, country) %>% 
    summarise(emission.GtCO2eq = sum(emission.ktCO2eq, na.rm = TRUE)/1E6) %>%
    group_by(country.code) %>% 
    summarise(emission.GtCO2eq = mean(emission.GtCO2eq)) %>% 
    ungroup() %>% 
    rename(gu_a3 = country.code)
}

if(!(any(input$sel_country == "Annex I"))){
  sel_country.code <- country.df %>% 
    filter(country %in% input$sel_country) %>% 
    select(country.code) %>% 
    as_vector()
  
  country.AnnexI_GHG.df <- country.AnnexI_GHG.df %>% 
    filter(gu_a3 %in% sel_country.code)
}

## Produce world map
world.sf <- ne_countries(scale = 'medium', returnclass = "sf")

## Merge GHG dataset with world map
GHG.world.sf <- merge(world.sf, country.AnnexI_GHG.df, all = TRUE)

## Calculate emissions per capita
GHG.world.sf <- GHG.world.sf %>% 
  mutate(pop_est = as.numeric(pop_est),
         emission.tCO2eq.per.cap = (emission.GtCO2eq*1E9)/pop_est)

## Make bins for color palette
minBin <- min(GHG.world.sf$emission.tCO2eq.per.cap, na.rm = TRUE)
maxBin <- max(GHG.world.sf$emission.tCO2eq.per.cap, na.rm = TRUE)
diffBin <- abs(maxBin-minBin)
rngExpand <- 0.10 ## expand fraction
addBuffer <- diffBin*rngExpand

bins <- pretty(seq(from = minBin-addBuffer, to = maxBin+addBuffer, length.out = 5))
print(bins)
## Color palette
pal <- colorBin("YlOrRd", domain = GHG.world.sf$emission.tCO2eq.per.cap, bins = bins)

## Setup labels
labels <- sprintf(
  "<strong>%s</strong><br/>%g tCO2 / capita",
  GHG.world.sf$sovereignt, round(GHG.world.sf$emission.tCO2eq.per.cap, digits = 2)
) %>% lapply(htmltools::HTML)


## Find boundaries
if(!(any(input$sel_country == "Annex I"))){
  bbox <- GHG.world.sf %>% 
    filter(gu_a3 %in% sel_country.code) %>% 
    st_bbox()
  lngSet <- as.vector(mean(bbox[1], bbox[3]))
  latSet <- as.vector(mean(bbox[2], bbox[4]))
  zoomSet = 3
}else{
  lngSet <- 0
  latSet <- 25
  zoomSet = 1.5
}

## Plot map
leaflet(GHG.world.sf) %>% 
  #setView(lng = 0, lat = 25, zoom = 1.3) %>% 
  setView(lng = lngSet, lat = latSet, zoom = zoomSet) %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(fillColor = ~pal(emission.tCO2eq.per.cap),
  weight = 2,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7,
  highlight = highlightOptions(
    weight = 3,
    color = "#666",
    dashArray = "",
    fillOpacity = 0.7,
    bringToFront = TRUE),
  label = labels,
  labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "15px",
    direction = "auto")) %>% 
  addLegend(pal = pal, values = ~emission.tCO2eq.per.cap, opacity = 0.7, title = NULL,
  position = "bottomright")


})

```




### Annual GHG emissions

```{r}

renderPlot({
  
  years_seq <- seq(input$sel_years[1], input$sel_years[2], by = 1)
  
  if(!(any(input$sel_country == "Annex I"))){
    tmp.AnnexI_GHG.df <- AnnexI_GHG.df %>% 
      filter(country %in% input$sel_country)
    
    if(input$sel_sector == "All"){
      
      tmp.AnnexI_GHG.df %>%
        filter(year %in% years_seq) %>% 
        group_by(sector, year, country) %>% 
        summarise(emission.MtCO2eq = sum(emission.ktCO2eq, na.rm = TRUE)/1E3) %>% 
        ggplot(aes(x = year, y = emission.MtCO2eq, fill = sector))+
        geom_col(colour = "black")+
        labs(y = "net emissions (Mt CO2eq)")+
        scale_x_continuous(breaks = years_seq)+
        scale_y_continuous(n.breaks = 20)+
        scale_fill_brewer(palette = "Pastel1")+
        theme_bw()+
        theme(axis.text.x = element_text(angle = 45, hjust = 0.9),
              legend.position = "bottom",
              aspect.ratio = 0.6)+
        guides(fill=guide_legend(nrow=2, byrow=TRUE))+
        facet_wrap(.~country)
      
    }else{

      tmp.AnnexI_GHG.df %>%
        filter(sector == input$sel_sector) %>% 
        filter(year %in% years_seq) %>% 
        group_by(IPCC_category, year, country) %>% 
        summarise(emission.MtCO2eq = sum(emission.ktCO2eq, na.rm = TRUE)/1E3) %>% 
        ggplot(aes(x = year, y = emission.MtCO2eq, fill = IPCC_category))+
        geom_col(colour = "black")+
        labs(y = "net emissions (Mt CO2eq)")+
        scale_x_continuous(breaks = years_seq)+
        scale_y_continuous(n.breaks = 20)+
        scale_fill_brewer(palette = "Pastel1")+
        theme_bw()+
        theme(axis.text.x = element_text(angle = 45, hjust = 0.9),
              legend.position = "bottom",
              aspect.ratio = 0.6)+
        guides(fill=guide_legend(nrow=2, byrow=TRUE))+
        facet_wrap(.~country)
      
    }
    
  }else{
    tmp.AnnexI_GHG.df <- AnnexI_GHG.df
    
    if(input$sel_sector == "All"){
      
      tmp.AnnexI_GHG.df %>%
        filter(year %in% years_seq) %>% 
        group_by(sector, year) %>% 
        summarise(emission.GtCO2eq = sum(emission.ktCO2eq, na.rm = TRUE)/1E6) %>% 
        ggplot(aes(x = year, y = emission.GtCO2eq, fill = sector))+
        geom_col(colour = "black")+
        labs(y = "net emissions (Gt CO2eq)")+
        scale_x_continuous(breaks = years_seq)+
        scale_y_continuous(n.breaks = 20)+
        scale_fill_brewer(palette = "Pastel1")+
        theme_bw()+
        theme(axis.text.x = element_text(angle = 45, hjust = 0.9),
              legend.position = "bottom",
              aspect.ratio = 0.6)+
        guides(fill=guide_legend(nrow=2, byrow=TRUE))
      
    }else{

      tmp.AnnexI_GHG.df %>%
        filter(sector == input$sel_sector) %>% 
        filter(year %in% years_seq) %>% 
        group_by(IPCC_category, year) %>% 
        summarise(emission.GtCO2eq = sum(emission.ktCO2eq, na.rm = TRUE)/1E6) %>% 
        ggplot(aes(x = year, y = emission.GtCO2eq, fill = IPCC_category))+
        geom_col(colour = "black")+
        labs(y = "net emissions (Gt CO2eq)")+
        scale_x_continuous(breaks = years_seq)+
        scale_y_continuous(n.breaks = 20)+
        scale_fill_brewer(palette = "Pastel1")+
        theme_bw()+
        theme(axis.text.x = element_text(angle = 45, hjust = 0.9),
              legend.position = "bottom",
              aspect.ratio = 0.6)+
        guides(fill=guide_legend(nrow=2, byrow=TRUE))
      
    }
  } 
})



```


Row {data-height=320}
-----------------------------------------------------------------------


### Table of total GHG emissions by sector

```{r}

## Produce table
renderTable({
  
  years_seq <- seq(input$sel_years[1], input$sel_years[2], by = 1)
  
  if(!(any(input$sel_country == "Annex I"))){
    if(input$sel_sector == "All"){
      AnnexI_GHG.df %>%
        filter(year %in% years_seq) %>%
        filter(country %in% input$sel_country) %>% 
        group_by(sector, country, year) %>%
        summarise(emission.MtCO2eq = sum(emission.ktCO2eq, na.rm = TRUE)/1E3) %>%
        mutate(unit = "Mt CO2eq") %>% 
        spread(year, emission.MtCO2eq)
    }else{
      AnnexI_GHG.df %>%
        filter(sector == input$sel_sector) %>% 
        filter(year %in% years_seq) %>% 
        filter(country %in% input$sel_country) %>% 
        group_by(IPCC_category, country, year) %>%
        summarise(emission.MtCO2eq = sum(emission.ktCO2eq, na.rm = TRUE)/1E3) %>%
        mutate(unit = "Mt CO2eq") %>% 
        spread(year, emission.MtCO2eq)
    }
  }else{
    if(input$sel_sector == "All"){
      AnnexI_GHG.df %>%
        filter(year %in% years_seq) %>%
        group_by(sector, year) %>%
        summarise(emission.GtCO2eq = sum(emission.ktCO2eq, na.rm = TRUE)/1E6) %>%
        mutate(unit = "Gt CO2eq") %>% 
        spread(year, emission.GtCO2eq)
    }else{
      AnnexI_GHG.df %>%
        filter(sector == input$sel_sector) %>% 
        filter(year %in% years_seq) %>% 
        group_by(IPCC_category, year) %>%
        summarise(emission.GtCO2eq = sum(emission.ktCO2eq, na.rm = TRUE)/1E6) %>%
        mutate(unit = "Gt CO2eq") %>% 
        spread(year, emission.GtCO2eq)
    }
  }
  
}, digits = 2)

```

